"""core/ -- framework-free domain dataclasses and enums (Module 3). Never imports infrastructure/."""

from core.models import (
    BotHealthSnapshot,
    BtcStatisticsSnapshot,
    Coin,
    CoinClassification,
    CoinProfile,
    CoinStatistics,
    ConfidenceGrade,
    ConfigSnapshot,
    ErrorEvent,
    FilterPerformance,
    MarketStatisticsSnapshot,
    MissedOpportunity,
    Rejection,
    RejectionReason,
    Report,
    ReportType,
    Signal,
    SignalDirection,
    SignalScoreComponent,
    Trade,
    TradeStatus,
)

__all__ = [
    "SignalDirection",
    "TradeStatus",
    "ConfidenceGrade",
    "CoinClassification",
    "ReportType",
    "RejectionReason",
    "Coin",
    "CoinProfile",
    "CoinStatistics",
    "Signal",
    "SignalScoreComponent",
    "Trade",
    "Rejection",
    "MissedOpportunity",
    "BtcStatisticsSnapshot",
    "MarketStatisticsSnapshot",
    "Report",
    "FilterPerformance",
    "BotHealthSnapshot",
    "ErrorEvent",
    "ConfigSnapshot",
]
